### ISSUE TITLE
Add t-shirt sizes to Tabs

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#688]
## Description
The design can be found on the [contributions](https://spectrum-contributions.corp.adobe.com/page/tabs-beta/).

## Tasks
* [ ] Use remapvars to reassign t-shirt sized variables
* [ ] Add migration guide that talks about the breaking changes
* [ ] Add an example showing different sizes of the component
